DROP TABLE public.confirmation_tokens;
DROP TABLE public.access_tokens;
DROP TABLE public.server_group_servers;
DROP TABLE public.history_items;
DROP TABLE public.server_groups;
DROP TABLE public.servers;
DROP TABLE public.settings;
DROP TABLE public.users;
DROP SEQUENCE public."Setting_setting_id_seq";